root_dir: ''
wandb_project_name: "script_modifications"
wandb_group_name: "ddp_training"
datasets:
    train: "train_coco_1_annotation_12000.json"
    val: "val_coco_1_annotation_12000.json"
    test: "test_coco_1_annotation_12000.json"
trainer:
    strategy: "ddp"
multistepLR:
    warmup_steps: 200
    milestones: [1000, 3000]
    gamma: 0.1
train_params:
    batch_size: 4
    epochs: 100
    lr: 0.005
    weight_decay: 0.0001  
    num_workers: 4
model_params:
    backbone_name: 'resnet18'
    num_classes: 6 
    aspect_ratios: [0.5, 1.0, 2.0, 4.0, 8.0]
    rpn_pre_nms_top_n_train: 12000
    rpn_pre_nms_top_n_test:  6000
    box_score_thresh: 0.5 #SCORE_THRESH_TEST: 0.5, both were 0.05 by default     
id2label: {1: 'table', 2: 'footer', 3: 'header', 4: 'order_line_item_header', 5: 'order_line_item'}

  
  
